### PR TITLE
Johns - Major updates for Back End functionality

### PR DESCRIPTION
**Pull request by johannsp**
Back End functionality for Microsoft Speech Continuous Recognition SDK and Microsoft Translator v3.00 REST API have been hooked up in script.js and connected to a early, out-date version of the Front End in index.html.  The downloaded SDK files are also added for the first time.

### CODE REVIEW

**Review by Mtunberg1104 — APPROVED** [review]

**Review by Mtunberg1104 — APPROVED** [review]

**Review by Mtunberg1104 — COMMENTED** [review]
The code changes we made are to make the application speak and translate.

**Review by Mtunberg1104 — APPROVED** [review]
Code is up to date

**Review by deyron9 — APPROVED** [review]

**Review by deyron9 — APPROVED** [review]

**Review by haymanotyealemu — APPROVED** [review]
The first page is merged

**Comment by johannsp** [comment]
This is the first major commit to master branch.  Next up will be the integration of up-to-date front end and back end.

**Pull request merged**
